-- CARSI Hub — Seed: Podcast Shows (22 industry podcasts)

INSERT INTO public.podcast_shows (slug, name, host, description, rss_url, spotify_url, apple_podcasts_url, industry_categories, tags, is_carsi_show, featured, published, country)
VALUES
  (
    'science-of-property-restoration',
    'The Science of Property Restoration',
    'CARSI',
    'The official CARSI podcast covering restoration science, IICRC standards, and industry trends for Australian professionals.',
    'https://anchor.fm/s/carsi/podcast/rss',
    NULL,
    NULL,
    '["restoration","water damage","mould remediation","carpet cleaning","indoor air quality"]',
    '["CARSI","restoration","Australia","IICRC"]',
    true,
    true,
    true,
    'AU'
  ),
  (
    'restoration-rundown',
    'Restoration Rundown',
    NULL,
    'Weekly industry news and analysis for restoration professionals in Australia and globally.',
    NULL,
    NULL,
    NULL,
    '["restoration","water damage","fire damage","mould remediation"]',
    '["restoration","industry news"]',
    false,
    false,
    true,
    'AU'
  ),
  (
    'hvac-school-podcast',
    'HVAC School Podcast',
    'Bryan Orr',
    'In-depth HVAC/R training, troubleshooting, and fundamentals from working technicians.',
    'https://www.hvacrschool.com/feed/podcast/',
    'https://open.spotify.com/show/0c2T1tsMJ1MaqPJQfBB9U8',
    'https://podcasts.apple.com/us/podcast/hvac-school-podcast/id1235135273',
    '["hvac","air conditioning","refrigeration"]',
    '["HVAC","refrigeration","training"]',
    false,
    true,
    true,
    'AU'
  ),
  (
    'restoration-realness',
    'Restoration Realness',
    NULL,
    'Behind-the-scenes stories and business tips from restoration contractors across Australia.',
    NULL,
    NULL,
    NULL,
    '["restoration","water damage"]',
    '["restoration","business","Australia"]',
    false,
    false,
    true,
    'AU'
  ),
  (
    'clean-talk',
    'Clean Talk',
    NULL,
    'Carpet cleaning, hard floor restoration, and surface care techniques for Australian cleaning professionals.',
    NULL,
    NULL,
    NULL,
    '["carpet cleaning","hard floor cleaning","commercial cleaning"]',
    '["carpet cleaning","Australia","techniques"]',
    false,
    false,
    true,
    'AU'
  ),
  (
    'iicrc-radio',
    'IICRC Radio',
    'IICRC',
    'Official podcast from the IICRC covering standards updates, certification paths, and restoration science globally.',
    NULL,
    NULL,
    NULL,
    '["restoration","standards","carpet cleaning","mould remediation"]',
    '["IICRC","standards","S500","S520"]',
    false,
    true,
    true,
    'AU'
  ),
  (
    'pest-files',
    'The Pest Files',
    NULL,
    'Pest management news, product reviews, and treatment techniques for Australian pest control professionals.',
    NULL,
    NULL,
    NULL,
    '["pest control"]',
    '["pest control","termites","Australia"]',
    false,
    false,
    true,
    'AU'
  ),
  (
    'indoor-air-talks',
    'Indoor Air Talks',
    NULL,
    'IAQ science, healthy buildings, and occupational hygiene for Australian health and restoration professionals.',
    NULL,
    NULL,
    NULL,
    '["indoor air quality","healthy homes","occupational hygiene"]',
    '["IAQ","healthy homes","Australia"]',
    false,
    false,
    true,
    'AU'
  ),
  (
    'building-science-podcast',
    'Building Science Podcast',
    NULL,
    'Moisture, thermal dynamics, and building enclosure science for restoration and construction professionals.',
    NULL,
    NULL,
    NULL,
    '["restoration","water damage","structural drying","healthy homes"]',
    '["building science","moisture","thermal"]',
    false,
    false,
    true,
    'AU'
  ),
  (
    'property-restoration-au',
    'Property Restoration Australia',
    NULL,
    'Australian-focused restoration business tips, case studies, and industry news for contractors and insurers.',
    NULL,
    NULL,
    NULL,
    '["restoration","insurance","disaster recovery"]',
    '["Australia","restoration","insurance","claims"]',
    false,
    false,
    true,
    'AU'
  ),
  (
    'flooring-pro-podcast',
    'Flooring Pro Podcast',
    NULL,
    'Professional flooring installation, maintenance, and business development for Australian floor covering specialists.',
    NULL,
    NULL,
    NULL,
    '["flooring","carpet cleaning"]',
    '["flooring","installation","Australia"]',
    false,
    false,
    true,
    'AU'
  ),
  (
    'refrigeration-mentor-podcast',
    'Refrigeration Mentor Podcast',
    NULL,
    'Advanced refrigeration and HVAC training for Australian and international technicians.',
    NULL,
    NULL,
    NULL,
    '["hvac","refrigeration","air conditioning"]',
    '["refrigeration","advanced","training"]',
    false,
    false,
    true,
    'AU'
  ),
  (
    'the-water-damage-podcast',
    'The Water Damage Podcast',
    NULL,
    'Structural drying science, claim management, and business operations for water damage restoration professionals.',
    NULL,
    NULL,
    NULL,
    '["restoration","water damage","structural drying"]',
    '["water damage","structural drying","claims"]',
    false,
    false,
    true,
    'AU'
  ),
  (
    'mould-masters-podcast',
    'Mould Masters Podcast',
    NULL,
    'Mould assessment, testing, and IICRC S520-compliant remediation techniques for Australian professionals.',
    NULL,
    NULL,
    NULL,
    '["mould remediation","indoor air quality","restoration"]',
    '["mould","S520","IICRC","Australia"]',
    false,
    false,
    true,
    'AU'
  ),
  (
    'fire-damage-pro',
    'Fire Damage Pro',
    NULL,
    'Fire and smoke damage restoration techniques, contents cleaning, and deodorisation for industry professionals.',
    NULL,
    NULL,
    NULL,
    '["restoration","fire damage"]',
    '["fire damage","smoke","deodorisation"]',
    false,
    false,
    true,
    'AU'
  ),
  (
    'the-cleaning-business-podcast',
    'The Cleaning Business Podcast',
    NULL,
    'Business development, marketing, and operations for Australian cleaning and restoration businesses.',
    NULL,
    NULL,
    NULL,
    '["carpet cleaning","commercial cleaning","restoration"]',
    '["cleaning","business","Australia","marketing"]',
    false,
    false,
    true,
    'AU'
  ),
  (
    'disaster-recovery-professionals',
    'Disaster Recovery Professionals',
    NULL,
    'Large-loss restoration, catastrophe response, and project management for Australian restoration companies.',
    NULL,
    NULL,
    NULL,
    '["restoration","disaster recovery","water damage","fire damage"]',
    '["large loss","CAT","disaster","Australia"]',
    false,
    false,
    true,
    'AU'
  ),
  (
    'healthy-homes-podcast',
    'Healthy Homes Podcast',
    NULL,
    'Indoor environment quality, allergen management, and home health for Australian homeowners and professionals.',
    NULL,
    NULL,
    NULL,
    '["healthy homes","indoor air quality"]',
    '["healthy homes","allergens","IAQ","Australia"]',
    false,
    false,
    true,
    'AU'
  ),
  (
    'insurance-claims-au',
    'Insurance Claims Australia',
    NULL,
    'Property claims management, builder/restorer relationships, and dispute resolution for Australian insurance professionals.',
    NULL,
    NULL,
    NULL,
    '["insurance","restoration","disaster recovery"]',
    '["insurance","claims","Australia","dispute"]',
    false,
    false,
    true,
    'AU'
  ),
  (
    'occupational-hygiene-down-under',
    'Occupational Hygiene Down Under',
    NULL,
    'Workplace health, hazardous substance management, and safety for Australian occupational hygienists.',
    NULL,
    NULL,
    NULL,
    '["occupational hygiene","indoor air quality","healthy homes"]',
    '["occupational hygiene","safety","Australia"]',
    false,
    false,
    true,
    'AU'
  ),
  (
    'asbestos-management-au',
    'Asbestos Management Australia',
    NULL,
    'Asbestos identification, management, and safe removal for Australian licensed removalists and building professionals.',
    NULL,
    NULL,
    NULL,
    '["restoration","occupational hygiene","healthy homes"]',
    '["asbestos","removal","Australia","safety"]',
    false,
    false,
    true,
    'AU'
  ),
  (
    'the-restoration-coach',
    'The Restoration Coach',
    NULL,
    'Business coaching, marketing, and operations for restoration company owners in Australia and globally.',
    NULL,
    NULL,
    NULL,
    '["restoration","water damage","fire damage"]',
    '["business coaching","restoration","marketing","growth"]',
    false,
    false,
    true,
    'AU'
  )
ON CONFLICT (slug) DO NOTHING;
